GMS.Web.Admin/Areas/OA/Controllers/BranchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GMS.OA.Contract;
using GMS.Account.Contract;
using GMS.Web.Admin.Common;
using GMS.Framework.Utility;

namespace GMS.Web.Admin.Areas.OA.Controllers
{
    [Permission(EnumBusinessPermission.OAManage_Branch)]
    public class BranchController : AdminControllerBase
    {
        //
        // GET: /OA/Branch/

        public ActionResult Index(BranchRequest request)
        {
            var result = this.OAService.GetBranchList(request);
            return View(result);
        }

        //
        // GET: /OA/Branch/Create

        public ActionResult Create()
        {
            var model = new Branch();
            return View("Edit", model);
        }

        //
        // POST: /OA/Branch/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            var model = new Branch();
            this.TryUpdateModel<Branch>(model);

            this.OAService.SaveBranch(model);

            return this.RefreshParent();
        }

        //
        // GET: /OA/Branch/Edit/5

        public ActionResult Edit(int id)
        {
            var model = this.OAService.GetBranch(id);
            return View(model);
        }

        //
        // POST: /OA/Branch/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            var model = this.OAService.GetBranch(id);
            this.TryUpdateModel<Branch>(model);

            this.OAService.SaveBranch(model);

            return this.RefreshParent();
        }

        // POST: /OA/Branch/Delete/5

        [HttpPost]
        public ActionResult Delete(List<int> ids)
        {
            this.OAService.DeleteBranch(ids);
            return RedirectToAction("Index");
        }
    }
}

GMS.Web.Admin/Areas/OA/Controllers/OrgController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using GMS.OA.Contract;
using GMS.Account.Contract;
using GMS.Web.Admin.Common;
using GMS.Framework.Utility;

namespace GMS.Web.Admin.Areas.OA.Controllers
{
    [Permission(EnumBusinessPermission.OAManage_Org)]
    public class OrgController : AdminControllerBase
    {
        //
        // GET: /OA/Org/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetOrg()
        {
            var rootBranch = this.OAService.GetOrg();

            return Json(rootBranch, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SaveOrg()
        {
            try
            {
                int bytelength = Request.ContentLength;
                byte[] inputbytes = Request.BinaryRead(bytelength);
                string message = System.Text.Encoding.UTF8.GetString(inputbytes);
                var branch = JsonConvert.DeserializeObject<Branch>(message);

                this.OAService.SaveOrg(branch);
            }
            catch (Exception e)
            {
                return Content(e.Message);
            }

            return Content("保存成功！");
        }
    }
}

GMS.Web.Admin/Areas/OA/Views/Branch/Edit.cshtml
@using GMS.Framework.Contract
@using GMS.Framework.Web.Controls
@using GMS.OA.Contract
@using GMS.Web
@model Branch
@{
    Layout = "~/Views/Shared/_Layout.Edit.cshtml";
}
@section PageSpecificStyleSheetIncludes{
}
@section PageSpecificJavascriptIncludes{
    <script type="text/javascript">
   </script>
}
@section MainContent{
<div class="portlet-body form-horizontal form-bordered form-row-stripped">
    <div class="row-fluid"> 
            <div class="control-group">
                <label class="control-label"><span class="required">*</span>名称：</label>
                <div class="controls">
                @Html.TextBoxFor(m => m.Name, new { @class = "m-wrap" })
                <span class="help-inline">@Html.ValidationMessageFor(m => m.Name)</span>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label">描述：</label>
                <div class="controls">
                @Html.TextBoxFor(m => m.Desc, new { @class = "m-wrap large" })
                <span class="help-inline">@Html.ValidationMessageFor(m => m.Desc)</span>
                </div>
            </div>
            
    </div>
</div>
}

GMS.Web.Admin/Areas/OA/Views/Branch/Index.cshtml
@using GMS.Framework.Contract
@using GMS.Framework.Utility
@using GMS.Framework.Web.Controls
@using GMS.OA.Contract

@model PagedList<Branch>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row-fluid">
    <div class="span4">
        <div>
            <a class="btn red" id="delete" href="javascript:;"><i class="icon-trash icon-white"></i> 删除</a>
            <a class="btn blue thickbox" title='添加新部门' href="@Url.Action("Create")?TB_iframe=true&height=200&width=450"><i class="icon-plus icon-white"></i> 新增</a>
        </div>
    </div>
    <div class="span8">
        @using (Html.BeginForm(null, null, null, FormMethod.Get, new { id = "search" }))
        { 
        <div class="dataTables_filter">
            <label>
                <button type="submit" class="btn">搜索 <i class="icon-search"></i></button>
             </label>
            <label>
                <span>名称：</span>
                @Html.TextBox("Name", null, new { @class = "m-wrap small" })
            </label>
        </div>
        }
    </div>
</div>
<div class="alert alert-info">
    <button class="close" data-dismiss="alert"></button>
    编辑部门从属关系（上级部门，下设部门）请到 <strong>“<a href="@Url.Action("Index", "Org")">组织结构管理</a>”</strong>菜单操作！
</div>

@using (Html.BeginForm("Delete", "Branch", FormMethod.Post, new { id = "mainForm" }))
{
<table class="table table-striped table-hover ">
    <thead>
        <tr>
            <th style="width: 8px;">
                <input type="checkbox" id="checkall" class="group-checkable" />
            </th>
            <th>
                名称
            </th>
            <th>
                描述
            </th>
            <th>
                操作
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var m in Model)
        {
        <tr>
            <td>
                <input type="checkbox" class="checkboxes" name='ids' value='@m.ID' />
            </td>
            <td>
                @m.Name
            </td>
            <td>
                @m.Desc
            </td>
            <td>
                <a class="btn mini purple thickbox" title='编辑部门内容' href="@Url.Action("Edit", new { id = m.ID })?TB_iframe=true&height=200&width=450">
                    <i class="icon-edit"></i>
                    编辑
                </a>
            </td>
        </tr>
        }
    </tbody>
</table>
}
<div class="dataTables_paginate paging_bootstrap pagination">
    @Html.Pager(Model, new PagerOptions() { ShowTotalItemCount = true })
</div>