GMS.Web.Admin/Areas/Crm/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GMS.Crm.Contract;
using GMS.Account.Contract;
using GMS.Web.Admin.Common;
using GMS.Framework.Utility;
using GMS.Framework.Contract;

namespace GMS.Web.Admin.Areas.Crm.Controllers
{
    [Permission(EnumBusinessPermission.CrmManage_Customer)]
    public class CustomerController : AdminControllerBase
    {
        //
        // GET: /Crm/Customer/

        public ActionResult Index(CustomerRequest request)
        {
            this.TryUpdateModel<Customer>(request.Customer);

            this.ModelState.Clear();
            
            this.RenderMyViewData(request.Customer, true);
            
            var result = this.CrmService.GetCustomerList(request);
            return View(result);
        }

        //
        // GET: /Crm/Customer/Create

        public ActionResult Create()
        {
            var model = new Customer();

            this.RenderMyViewData(model);

            return View("Edit", model);
        }

        //
        // POST: /Crm/Customer/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            var model = new Customer();
            this.TryUpdateModel<Customer>(model);

            try
            {
                this.CrmService.SaveCustomer(model);
            }
            catch (BusinessException e)
            {
                this.ModelState.AddModelError(e.Name, e.Message);
                this.RenderMyViewData(model);
                return View("Edit", model);
            }
            

            return this.RefreshParent();
        }

        //
        // GET: /Crm/Customer/Edit/5

        public ActionResult Edit(int id)
        {
            var model = this.CrmService.GetCustomer(id);
            this.RenderMyViewData(model);
            return View(model);
        }

        //
        // POST: /Crm/Customer/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            var model = this.CrmService.GetCustomer(id);
            this.TryUpdateModel<Customer>(model);

            try
            {
                this.CrmService.SaveCustomer(model);
            }
            catch (BusinessException e)
            {
                this.ModelState.AddModelError(e.Name, e.Message);
                this.RenderMyViewData(model);
                return View("Edit", model);
            }

            return this.RefreshParent();
        }

        // POST: /Crm/Customer/Delete/5

        [HttpPost]
        public ActionResult Delete(List<int> ids)
        {
            this.CrmService.DeleteCustomer(ids);
            return RedirectToAction("Index");
        }

        private void RenderMyViewData(Customer model, bool isBasic = false)
        {
            ViewData.Add("Gender", new SelectList(EnumHelper.GetItemValueList<EnumGender>(), "Key", "Value", model.Gender));
            ViewData.Add("Category", new SelectList(EnumHelper.GetItemValueList<EnumCategory>(), "Key", "Value", model.Category));
            ViewData.Add("Profession", new SelectList(EnumHelper.GetItemValueList<EnumProfession>(), "Key", "Value", model.Profession));
            ViewData.Add("AgeGroup", new SelectList(EnumHelper.GetItemValueList<EnumAgeGroup>(), "Key", "Value", model.AgeGroup));

            if (isBasic)
                return;

            ViewData.Add("UserId", new SelectList(this.AccountService.GetUserList(), "ID", "LoginName", model.UserId));
        }
    }
}

GMS.Web.Admin/Areas/Crm/Controllers/VisitRecordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GMS.Crm.Contract;
using GMS.Account.Contract;
using GMS.Web.Admin.Common;
using GMS.Framework.Utility;
using GMS.Framework.Contract;
using GMS.Core.Cache;

namespace GMS.Web.Admin.Areas.Crm.Controllers
{
    [Permission(EnumBusinessPermission.CrmManage_VisitRecord)]
    public class VisitRecordController : AdminControllerBase
    {
        //
        // GET: /Crm/VisitRecord/

        public ActionResult Index(VisitRecordRequest request)
        {
            this.TryUpdateModel<VisitRecord>(request.VisitRecord);

            this.ModelState.Clear();
            
            this.RenderMyViewData(request.VisitRecord, true);
            var areas = this.AreaDic.Values.Select(c => new { Id = c.ID, Name = c.Name + "-" + this.CityDic[c.CityId].Name });
            ViewData.Add("AreaId", new SelectList(areas, "Id", "Name", request.VisitRecord.AreaId));
            
            var result = this.CrmService.GetVisitRecordList(request);
            return View(result);
        }

        //
        // GET: /Crm/VisitRecord/Create

        public ActionResult Create()
        {
            var model = new VisitRecord();

            this.RenderMyViewData(model);

            return View("Edit", model);
        }

        //
        // POST: /Crm/VisitRecord/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            var model = new VisitRecord();
            this.TryUpdateModel<VisitRecord>(model);

            model.CreateTime = model.VisitTime = DateTime.Now;
            model.Username = this.UserContext.LoginInfo.LoginName;
            model.UserId = this.UserContext.LoginInfo.UserID;

            try
            {
                this.CrmService.SaveVisitRecord(model);
            }
            catch (BusinessException e)
            {
                this.ModelState.AddModelError(e.Name, e.Message);
                this.RenderMyViewData(model);
                return View("Edit", model);
            }
            

            return this.RefreshParent();
        }

        //
        // GET: /Crm/VisitRecord/Edit/5

        public ActionResult Edit(int id)
        {
            var model = this.CrmService.GetVisitRecord(id);
            this.RenderMyViewData(model);
            return View(model);
        }

        //
        // POST: /Crm/VisitRecord/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            var model = this.CrmService.GetVisitRecord(id);
            this.TryUpdateModel<VisitRecord>(model);

            try
            {
                this.CrmService.SaveVisitRecord(model);
            }
            catch (BusinessException e)
            {
                this.ModelState.AddModelError(e.Name, e.Message);
                this.RenderMyViewData(model);
                return View("Edit", model);
            }

            return this.RefreshParent();
        }

        // POST: /Crm/VisitRecord/Delete/5

        [HttpPost]
        public ActionResult Delete(List<int> ids)
        {
            this.CrmService.DeleteVisitRecord(ids);
            return RedirectToAction("Index");
        }

        public ActionResult GetArea(int cityId)
        {
            var areas = this.AreaDic.Values.Where(a => a.CityId == cityId);
            ViewData.Add("AreaId", new SelectList(areas, "Id", "Name"));

            return PartialView("AreaSelect");
        }

        private void RenderMyViewData(VisitRecord model, bool isBasic = false)
        {
            ViewData.Add("VisitWay", new SelectList(EnumHelper.GetItemValueList<EnumVisitWay>(), "Key", "Value", model.VisitWay));
            ViewData.Add("FollowLevel", new SelectList(EnumHelper.GetItemValueList<EnumFollowLevel>(), "Key", "Value", model.FollowLevel));
            ViewData.Add("FollowStep", new SelectList(EnumHelper.GetItemValueList<EnumFollowStep>(), "Key", "Value", model.FollowStep));
            ViewData.Add("ProductType", new SelectList(EnumHelper.GetItemValueList<EnumProductType>(), "Key", "Value", model.ProductType));

            ViewData.Add("Focus", new SelectList(EnumHelper.GetItemList<EnumFocus>(), "Key", "Value", (EnumFocus)model.Focus));
            ViewData.Add("CognitiveChannel", new SelectList(EnumHelper.GetItemList<EnumCognitiveChannel>(), "Key", "Value", (EnumCognitiveChannel)model.CognitiveChannel));
            ViewData.Add("PriceResponse", new SelectList(EnumHelper.GetItemValueList<EnumPriceResponse>(), "Key", "Value", model.PriceResponse));
            ViewData.Add("AreaDemand", new SelectList(EnumHelper.GetItemValueList<EnumAreaDemand>(), "Key", "Value", model.AreaDemand));
            ViewData.Add("Motivation", new SelectList(EnumHelper.GetItemValueList<EnumMotivation>(), "Key", "Value", model.Motivation));

            ViewData.Add("ProjectId", new SelectList(this.CrmService.GetProjectList(), "Id", "Name", model.ProjectId));

            if (isBasic)
                return;

            ViewData.Add("CityId", new SelectList(this.CityDic.Values, "Id", "Name", model.CityId));

            if (model.CityId == 0)
                model.CityId = this.CityDic.First().Key;

            var areas = this.AreaDic.Values.Where(a => a.CityId == model.CityId);
            ViewData.Add("AreaId", new SelectList(areas, "Id", "Name", model.AreaId));

            var request = new CustomerRequest();
            request.Customer.UserId = this.UserContext.LoginInfo.UserID;
            var customerList = this.CrmService.GetCustomerList(request).ToList();
            customerList.ForEach(c => c.Name = string.Format("{0}({1})", c.Name, c.Tel));
            ViewData.Add("CustomerId", new SelectList(customerList, "Id", "Name", model.CustomerId));

        }

        public Dictionary<int, City> CityDic
        {
            get
            {
                return AdminCacheContext.Current.CityDic;
            }
        }

        public Dictionary<int, Area> AreaDic
        {
            get
            {
                return AdminCacheContext.Current.AreaDic;
            }
        }
    }
}

GMS.Web.Admin/Areas/Crm/Views/Customer/Edit.cshtml
@using GMS.Framework.Contract
@using GMS.Framework.Web.Controls
@using GMS.Crm.Contract
@using GMS.Web
@model Customer
@{
    Layout = "~/Views/Shared/_Layout.Edit.cshtml";
}
@section PageSpecificStyleSheetIncludes{
    <style type="text/css">
        .controls label
        {
            display:inline;
        }
    </style>
}
@section PageSpecificJavascriptIncludes{
}
@section MainContent{
<div class="portlet-body form-horizontal form-bordered form-row-stripped">
    <div class="row-fluid"> 

            <div class="control-group">
                <label class="control-label"><span class="required">*</span>客户姓名：</label>
                <div class="controls">
                @Html.TextBoxFor(m => m.Name, new { @class = "m-wrap" })
                <span class="help-inline">@Html.ValidationMessageFor(m => m.Name)</span>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label"><span class="required">*</span>客户编号：</label>
                <div class="controls">
                @Html.TextBoxFor(m => m.Number, new { @class = "m-wrap" })
                <span class="help-inline">@Html.ValidationMessageFor(m => m.Number)</span>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label"><span class="required">*</span>客户电话：</label>
                <div class="controls">
                @Html.TextBoxFor(m => m.Tel, new { @class = "m-wrap" })
                <span class="help-inline">@Html.ValidationMessageFor(m => m.Tel)</span>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label"><span class="required">*</span>电子邮件：</label>
                <div class="controls">
                @Html.TextBoxFor(m => m.Email, new { @class = "m-wrap" })
                <span class="help-inline">@Html.ValidationMessageFor(m => m.Email)</span>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label"><span class="required">*</span>通讯地址：</label>
                <div class="controls">
                @Html.TextBoxFor(m => m.Address, new { @class = "m-wrap" })
                <span class="help-inline">@Html.ValidationMessageFor(m => m.Address)</span>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label"><span class="required">*</span>性别：</label>
                <div class="controls">
                @Html.RadioBoxList("Gender")   
                <span class="help-inline">@Html.ValidationMessageFor(m => m.Gender)</span>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label"><span class="required">*</span>客户类型：</label>
                <div class="controls">
                @Html.RadioBoxList("Category")   
                <span class="help-inline">@Html.ValidationMessageFor(m => m.Category)</span>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label"><span class="required">*</span>职业：</label>
                <div class="controls">
                @Html.RadioBoxList("Profession")   
                <span class="help-inline">@Html.ValidationMessageFor(m => m.Profession)</span>
                </div>
            </div>

            <div class="control-group">
                <label class="control-label"><span class="required">*</span>客户年龄：</label>
                <div class="controls">
                @Html.RadioBoxList("AgeGroup")   
                <span class="help-inline">@Html.ValidationMessageFor(m => m.AgeGroup)</span>
                </div>
            </div>

    </div>
</div>
}

GMS.Web.Admin/Areas/Crm/Views/Customer/Index.cshtml
@using GMS.Framework.Contract
@using GMS.Framework.Utility
@using GMS.Framework.Web.Controls
@using GMS.Crm.Contract

@model PagedList<Customer>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section PageSpecificStyleSheetIncludes{
    <style type="text/css"> 
        select { margin:1px; width:150px;}
    </style>
}
<div class="row-fluid">
    <div class="span1">
        <div>
            <a class="btn blue thickbox" title='添加新客户' href="@Url.Action("Create")?TB_iframe=true&height=600&width=600"><i class="icon-plus icon-white"></i> 新增</a>
            <br />
            <a class="btn red" id="delete" href="javascript:;"><i class="icon-trash icon-white"></i> 删除</a>
        </div>
    </div>
    <div class="span11">
        @using (Html.BeginForm(null, null, null, FormMethod.Get, new { id = "search", @class = "form-inline" }))
        { 
        <div>
            置业顾问：@Html.TextBox("username", Request["username"], new { @class = "m-wrap small" })&nbsp;
             客户名：@Html.TextBox("name", Request["name"], new { @class = "m-wrap small" })&nbsp;
             客户编号：@Html.TextBox("number", Request["number"], new { @class = "m-wrap small" })&nbsp;
             客户电话：@Html.TextBox("tel", Request["tel"], new { @class = "m-wrap small" })&nbsp;
         </div>
            <div class="p10">
             性别：@Html.DropDownList("Gender", "全部")&nbsp;
            类型：@Html.DropDownList("Category", "全部")&nbsp;
            职业：@Html.DropDownList("Profession", "全部")&nbsp;
            年龄：@Html.DropDownList("AgeGroup", "全部")&nbsp;
            <button type="submit" class="btn">搜索 <i class="icon-search"></i></button>
      
        </div>
        }
    </div>
</div>

@using (Html.BeginForm("Delete", "Customer", FormMethod.Post, new { id = "mainForm" }))
{
<table class="table table-striped table-hover ">
    <thead>
        <tr>
            <th style="width: 8px;">
                <input type="checkbox" id="checkall" class="group-checkable" />
            </th>
            <th >
                客户名
            </th>
            <th >
                编号
            </th>
            <th >
                电话
            </th>
            <th >
                性别
            </th>
            <th >
                类型
            </th>
            <th >
                年龄
            </th>
            <th >
                职业
            </th>
            <th >
                置业顾问
            </th>
            <th >
                添加时间
            </th>     
            <th >
                来电数
            </th> 
            <th>
                操作
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var p in Model)
        {
        <tr>
            <td>
                <input type="checkbox" class="checkboxes" name='ids' value='@p.ID' />
            </td>
            <td  class="blue">
                <span>@p.Name</span>
            </td>
            <td>
                <span>@p.Number</span>
            </td>
            <td>
                <span>@p.Tel</span>
            </td>
            <td>
                <span>@EnumHelper.GetEnumTitle((EnumGender)p.Gender)</span>
            </td>
            <td>
                <span>@EnumHelper.GetEnumTitle((EnumCategory)p.Category)</span>
            </td>
             <td>
                <span>@EnumHelper.GetEnumTitle((EnumAgeGroup)p.AgeGroup)</span>
            </td>
            <td>
                <span>@EnumHelper.GetEnumTitle((EnumProfession)p.Profession)</span>
            </td>
            <td class="green">
                <span>@p.Username</span>
            </td>
            <td>
                <span>@p.CreateTime.ToCnDataString()</span>
            </td>
            <td class="toolbar">
                    @p.VisitRecords.Count <a href="@Url.Action("Index", "VisitRecord")?Customer.Tel=@p.Tel" target="_blank">查看来电</a>
            </td>
            <td>
                <a class="btn mini purple thickbox" title='编辑客户内容' href="@Url.Action("Edit", new { id = p.ID })?TB_iframe=true&height=600&width=600">
                    <i class="icon-edit"></i>
                    编辑
                </a>
            </td>
        </tr>
        }
    </tbody>
</table>
}
<div class="dataTables_paginate paging_bootstrap pagination">
    @Html.Pager(Model, new PagerOptions() { ShowTotalItemCount = true })
</div>